// Danee Shoes Care — Order Service
// Full order management

import { getSupabase } from '../supabase';
import type {
  OrderRow,
  OrderCreate,
  OrderUpdate,
  OrderStatus,
  OrderItemRow,
  OrderItemCreate,
  ServiceResponse,
} from '../types-supabase';

const TABLE = 'orders';

/**
 * Get all orders, with optional status filter
 * Ordered by tanggal descending (newest first)
 */
export async function getAll(
  status?: OrderStatus
): Promise<ServiceResponse<OrderRow[]>> {
  try {
    const supabase = getSupabase();
    let query = supabase
      .from(TABLE)
      .select('*')
      .order('tanggal', { ascending: false });

    if (status) {
      query = query.eq('status', status);
    }

    const { data, error } = await query;

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, data: data || [] };
  } catch (err: any) {
    return { success: false, error: err.message || 'Gagal mengambil data order' };
  }
}

/**
 * Get single order by id
 */
export async function getById(
  id: string
): Promise<ServiceResponse<OrderRow>> {
  try {
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from(TABLE)
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, data };
  } catch (err: any) {
    return { success: false, error: err.message || 'Gagal mengambil data order' };
  }
}

/**
 * Lookup order by kode (order code)
 */
export async function getByKode(
  kode: string
): Promise<ServiceResponse<OrderRow>> {
  try {
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from(TABLE)
      .select('*')
      .eq('kode', kode)
      .single();

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, data };
  } catch (err: any) {
    return { success: false, error: err.message || 'Gagal mencari order berdasarkan kode' };
  }
}

/**
 * Create a new order
 * Kode (ORD-XXX) auto-generated by DB trigger trg_orders_kode via sequence
 * Bayar di Awal: cashflow entry should be created by caller or edge function
 */
export async function create(
  payload: OrderCreate
): Promise<ServiceResponse<OrderRow>> {
  try {
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from(TABLE)
      .insert({
        // kode: auto-generated by DB trigger trg_orders_kode
        nama_pelanggan: payload.nama_pelanggan,
        kontak_wa: payload.kontak_wa || null,
        layanan: payload.layanan,
        harga: payload.harga,
        catatan: payload.catatan || null,
        diskon_info: payload.diskon_info || null,
        referral: payload.referral || null,
        tipe_pembayaran: payload.tipe_pembayaran || 'Bayar di Akhir',
      })
      .select()
      .single();

    if (error) {
      return { success: false, error: error.message };
    }

    // Simpan structured items (FASE 1)
    if (payload.items && payload.items.length > 0 && data) {
      await saveOrderItems(data.id, payload.items);
    }

    return { success: true, data };
  } catch (err: any) {
    return { success: false, error: err.message || 'Gagal membuat order' };
  }
}

/**
 * Save structured order_items (FASE 1)
 * Replaces all items for an order (delete + insert)
 */
export async function saveOrderItems(
  orderId: string,
  items: OrderItemCreate[]
): Promise<ServiceResponse<OrderItemRow[]>> {
  try {
    const supabase = getSupabase();

    // Delete existing items
    await supabase
      .from('order_items')
      .delete()
      .eq('order_id', orderId);

    // Insert new items
    const inserts = items.map((item, idx) => ({
      order_id: orderId,
      service_id: item.service_id || null,
      store_id: item.store_id || null,
      tipe: item.tipe,
      nama_item: item.nama_item,
      qty: item.qty,
      harga_satuan: item.harga_satuan,
      diskon_per_item: item.diskon_per_item || 0,
      subtotal: item.subtotal,
      urutan: item.urutan || idx + 1,
    }));

    const { data, error } = await supabase
      .from('order_items')
      .insert(inserts)
      .select();

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, data: data || [] };
  } catch (err: any) {
    return { success: false, error: err.message || 'Gagal menyimpan item order' };
  }
}

/**
 * Load structured order_items for an order
 */
export async function getOrderItems(
  orderId: string
): Promise<ServiceResponse<OrderItemRow[]>> {
  try {
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from('order_items')
      .select('*')
      .eq('order_id', orderId)
      .order('urutan', { ascending: true });

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, data: data || [] };
  } catch (err: any) {
    return { success: false, error: err.message || 'Gagal memuat item order' };
  }
}

/**
 * Update order status
 * Validates against allowed status transitions
 */
export async function updateStatus(
  id: string,
  newStatus: OrderStatus
): Promise<ServiceResponse<OrderRow>> {
  try {
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from(TABLE)
      .update({ status: newStatus })
      .eq('id', id)
      .select()
      .single();

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, data };
  } catch (err: any) {
    return { success: false, error: err.message || 'Gagal mengupdate status order' };
  }
}

/**
 * Full order update (edit order details)
 */
export async function update(
  id: string,
  payload: OrderUpdate
): Promise<ServiceResponse<OrderRow>> {
  try {
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from(TABLE)
      .update(payload)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      return { success: false, error: error.message };
    }

    // Update items if provided (FASE 1)
    if (payload.items && data) {
      await saveOrderItems(data.id, payload.items);
    }

    return { success: true, data };
  } catch (err: any) {
    return { success: false, error: err.message || 'Gagal mengupdate order' };
  }
}

/**
 * Public tracking: search orders by kode, kontak_wa, or nama_pelanggan
 */
export async function trackOrder(
  keyword: string
): Promise<ServiceResponse<OrderRow[]>> {
  try {
    const supabase = getSupabase();
    const keywordLower = keyword.toLowerCase().trim();

    // Pake RPC function yang bypass RLS (SECURITY DEFINER)
    const { data, error } = await supabase
      .rpc('search_orders', { keyword: keywordLower });

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, data: data || [] };
  } catch (err: any) {
    return { success: false, error: err.message || 'Gagal melacak order' };
  }
}
